apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: two-tier-ingress
  namespace: two-tier-flask-mysql
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing   
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              number: 80
