apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-entrypoint-query-configmap
  namespace: two-tier-flask-mysql
data: 
  init.sql: |
    CREATE DATABASE IF NOT EXISTS testdb;
    USE testdb;
    CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, message TEXT);
